# 广告牌创建价格
ad-price: 2000
# 广告牌介绍字数长度限制
ad-length: 16

# 使用龙泪最大装备强化次数
max-upgrade-count: 6
# 默认装备强化次数
upgrade-count: 4
# 强化清除价格
upgrade-price: 5000
# 强化清除价格
upgrade-clear-price: 2000
# 修复物品价格
fix-item-price: 2000

# 开启强化属性
enable-attribute: false

# 定制物品名字价格
item-name-price: 20
# 定制物品名字限制长度
item-name-max-length: 6
# 定制物品名字次数不足执行指令
item-name-command: "/mp buy 定制物品名称"