name: RanLottery
main: cc.ranmc.lottery.Main
description: '桃花源定制24k纯钛合金超级无敌终终终终极版的BukkitPlugin插件'
website: https://www.ranmc.cc/
author: Ranica
version: Release 1.0
softdepend:
  - PlaceholderAPI

permissions:
  ranl.user:
    default: true
    description: 'user only'

  ranl.admin:
    default: op
    description: 'admin only'

commands:
  ranl:
    description: ranl
    usage: /<command>