name: RanOnlineApi
main: cc.ranmc.online.Main
description: '阿然定制24k纯钛合金超级无敌终终终终极版的查询在线插件'
website: https://www.ranmc.cc/
author: Ranica
api-version: "1.13"
version: Release 4.0
folia-supported: true
softdepend: [Vault]

permissions:
  roa.user:
    default: true
    description: 'user only'

  roa.admin:
    default: op
    description: 'admin only'

  roa.joinfullserver:
    default: op
    description: 'join full server'

  roa.vip:
    default: op
    description: 'vip'

commands:
  roa:
    description: roa
    usage: /<command>

  ad:
    description: ad
    usage: /<command>

  vai:
    description: vai
    usage: /<command>

  attribute:
    description: attribute
    usage: /<command>

  cancelinput:
    description: cancelinput
    usage: /<command>