name: RanOnlineApi
main: cc.ranmc.api.Main
description: '阿然定制24k纯钛合金超级无敌终终终终极版的查询在线插件'
website: https://www.ranmc.cc/
author: Ranica
api-version: "1.13"
version: Release 1.1
folia-supported: true

permissions:
  roa.user:
    default: true
    description: 'user only'

  roa.admin:
    default: op
    description: 'admin only'

commands:
  roa:
    description: rancmd
    usage: /<command>