name: RanmcGuard
main: cc.ranmc.guard.Main
description: '阿然定制24k纯钛合金超级无敌终终终终极版的安全插件'
website: https://www.ranmc.cc/
author: Ranica
api-version: "21.1"
softdepend: [Ranmc]
version: ${project.version}

permissions:
  rg.user:
    default: true
    description: 'user only'

  rg.admin:
    default: op
    description: 'admin only'

commands:
  rg:
    description: rg
    usage: /<command>