name: RanCmd
main: cc.ranmc.rancmd.Main
description: '阿然定制24k纯钛合金超级无敌终终终终极版的指令插件'
website: https://www.ranmc.cc/
author: Ranica
api-version: "1.13"
version: ${project.version}

permissions:
  rancmd.user:
    default: true
    description: 'user only'

  rancmd.admin:
    default: op
    description: 'admin only'

commands:
  rancmd:
    description: rancmd
    usage: /<command>